/********************************************************************
* JunDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JunDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJunDict();
extern void G__cpp_setup_inheritanceJunDict();
extern void G__cpp_setup_typetableJunDict();
extern void G__cpp_setup_memvarJunDict();
extern void G__cpp_setup_globalJunDict();
extern void G__cpp_setup_memfuncJunDict();
extern void G__cpp_setup_funcJunDict();
extern void G__set_cpp_environmentJunDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/Users/fengjun/CodesAtGitHub/uiDAQ/include/mainFrame.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JunDictLN_TObject;
extern G__linked_taginfo G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JunDictLN_TQObject;
extern G__linked_taginfo G__JunDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JunDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JunDictLN_TGObject;
extern G__linked_taginfo G__JunDictLN_TGWindow;
extern G__linked_taginfo G__JunDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__JunDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JunDictLN_TGFrame;
extern G__linked_taginfo G__JunDictLN_TGCompositeFrame;
extern G__linked_taginfo G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__JunDictLN_TGTextButton;
extern G__linked_taginfo G__JunDictLN_TGVerticalFrame;
extern G__linked_taginfo G__JunDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__JunDictLN_TGMainFrame;
extern G__linked_taginfo G__JunDictLN_vectorlEcharcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEcharcOallocatorlEchargRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JunDictLN_TGTextViewostream;
extern G__linked_taginfo G__JunDictLN_TGTextEntry;
extern G__linked_taginfo G__JunDictLN_mainFrame;

/* STUB derived class for protected member access */
